import * as fs from 'fs';
import * as path from 'path';
import * as vm from 'vm';
import type { PluginSpec } from './spec-generator';

const VALID_IDENTIFIER = /^[a-zA-Z_][a-zA-Z0-9_]*$/;

/** Escape a string for safe embedding in JS string literals */
function escapeJsString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '\\r');
}

/** Validate that a parameter name is a safe JS identifier */
function validateParamName(name: string): string {
  if (!VALID_IDENTIFIER.test(name)) {
    throw new Error(`Invalid parameter name: ${name}`);
  }
  return name;
}

export function generatePluginCode(spec: PluginSpec, pluginDir: string): void {
  fs.mkdirSync(path.join(pluginDir, 'src'), { recursive: true });
  fs.mkdirSync(path.join(pluginDir, 'mcp'), { recursive: true });
  fs.mkdirSync(path.join(pluginDir, 'skill'), { recursive: true });

  // Update entryPoint to src/index.js
  const updatedSpec = { ...spec, entryPoint: 'src/index.js' };

  // Write plugin.spec.json
  fs.writeFileSync(
    path.join(pluginDir, 'plugin.spec.json'),
    JSON.stringify(updatedSpec, null, 2),
  );

  // Generate tool.json manifest
  const toolManifest = {
    pluginId: spec.id,
    pluginName: spec.name,
    version: spec.version,
    tools: spec.tools,
  };
  fs.writeFileSync(
    path.join(pluginDir, 'tool.json'),
    JSON.stringify(toolManifest, null, 2),
  );

  // Generate src/index.js entry point — all user-controlled strings are escaped
  const safeName = escapeJsString(spec.name);
  const safeDesc = escapeJsString(spec.description);
  const safeVersion = escapeJsString(spec.version);

  const toolHandlers = spec.tools
    .map((tool) => {
      const safeToolName = escapeJsString(tool.name);
      const safeToolDesc = escapeJsString(tool.description);
      const validatedParams = Object.keys(tool.parameters).map(validateParamName);
      const paramList = validatedParams.join(', ');
      return `  '${safeToolName}': function(${paramList}) {
    // TODO: implement ${safeToolDesc}
    console.log('[${safeName}] ${safeToolName} called', { ${paramList} });
    return { success: true };
  }`;
    })
    .join(',\n');

  const indexCode = `// Plugin: ${safeName}
// ${safeDesc}
// Version: ${safeVersion}
// Generated by AIDE plugin pipeline

var tools = {
${toolHandlers}
};

module.exports = {
  name: '${safeName}',
  version: '${safeVersion}',
  tools: tools,

  /**
   * Invoke a tool by name with the given arguments.
   * @param {string} toolName
   * @param {Record<string, unknown>} args
   */
  invoke: function(toolName, args) {
    var tool = tools[toolName];
    if (!tool) {
      throw new Error('Unknown tool: ' + toolName);
    }
    var params = Object.values(args || {});
    return tool.apply(null, params);
  },
};
`;

  fs.writeFileSync(path.join(pluginDir, 'src', 'index.js'), indexCode);
}

/** Write agent-provided real code instead of stubs */
export function generatePluginFromAgent(
  spec: PluginSpec,
  code: string,
  pluginDir: string,
): void {
  // Validate code compiles before writing
  try {
    vm.compileFunction(code, [], { filename: 'index.js' });
  } catch (err) {
    fs.rmSync(pluginDir, { recursive: true, force: true });
    throw new Error(`Plugin code compilation failed: ${(err as Error).message}`);
  }

  // Resolve the entry path from the spec; create parent dirs as needed
  const entryPath = path.join(pluginDir, spec.entryPoint);
  fs.mkdirSync(path.dirname(entryPath), { recursive: true });
  fs.mkdirSync(path.join(pluginDir, 'mcp'), { recursive: true });
  fs.mkdirSync(path.join(pluginDir, 'skill'), { recursive: true });

  fs.writeFileSync(
    path.join(pluginDir, 'plugin.spec.json'),
    JSON.stringify(spec, null, 2),
  );

  const toolManifest = {
    pluginId: spec.id,
    pluginName: spec.name,
    version: spec.version,
    tools: spec.tools,
  };
  fs.writeFileSync(
    path.join(pluginDir, 'tool.json'),
    JSON.stringify(toolManifest, null, 2),
  );

  fs.writeFileSync(entryPath, code);
}
